swagger: '2.0'
info:
  version: ''
  title: SMS Gateway API
  description: ''
host: 'localhost:8080'
basePath: /api/v1
schemes:
  - http
paths:
  /message:
    post:
      operationId: POST_message
      summary: Send SMS
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/trait:jsonHeader:Content-Type'
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      default: message
                      enum:
                        - message
                    id:
                      type: string
                    href:
                      type: string
                    body:
                      type: string
                    created_at:
                      type: integer
                  required:
                    - type
                    - id
                    - href
                    - body
                    - created_at
            required:
              - data
          examples:
            application/json:
              data:
                - type: message
                  id: 28f04c
                  href: 'https://rest.messagebird.com/messages/12345'
                  body: Bacon ipsum dolor amet ribs jerky.
                  created_at: 1496273045
        '400':
          $ref: '#/responses/trait:errors:400'
        '405':
          $ref: '#/responses/trait:errors:405'
        '500':
          $ref: '#/responses/trait:errors:500'
parameters:
  'trait:jsonHeader:Content-Type':
    name: Content-Type
    in: header
    required: true
    type: string
    default: application/json
    enum: '[application/json]'
responses:
  'trait:errors:400':
    description: ''
    schema:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/definitions/error'
            description: Bad Request
  'trait:errors:405':
    description: ''
    schema:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/definitions/error'
            description: Method Not Allowed
  'trait:errors:500':
    description: ''
    schema:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/definitions/error'
            description: Internal Server Error
definitions:
  sms:
    title: SMS
    type: object
    properties:
      recipient:
        type: string
      originator:
        type: string
      message:
        type: string
    required:
      - recipient
      - originator
      - message
    example:
      recipient: '+36701234567'
      originator: '+31201234567'
      message: Hello world!
  error:
    title: Error
    type: object
    example:
      status: '429'
      code: ERROR_TOO_MANY_REQUESTS
      title: Too Many Requests
      detail: 'You have sent too many requests and exceeded the API limit. Please, wait.'
    properties:
      status:
        type: string
        description: 'the HTTP status code applicable to this problem, expressed as a string value'
      code:
        type: string
        description: 'an application-specific error code, expressed as a string value'
      title:
        type: string
        description: 'a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization'
      detail:
        type: string
        description: 'a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized'
    required:
      - status
      - code
      - title